/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creer un compte */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Compte cree */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Email deja utilise */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Se connecter */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Connexion reussie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Identifiants invalides */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renouveler le token via le refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Nouveau couple de tokens */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Refresh token invalide, expire ou deja utilise */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister mes workspaces */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des workspaces de l'utilisateur courant */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDto"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Creer un workspace */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Workspace cree, le createur devient Admin */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDto"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les membres d'un workspace */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["WorkspaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des membres */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceMemberDto"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Inviter un membre (par email, doit deja avoir un compte) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["WorkspaceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Membre invite */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceMemberDto"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Aucun utilisateur avec cet email */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Deja membre du workspace */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/members/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Changer le role d'un membre (reserve aux Admin) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["WorkspaceId"];
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        role: components["schemas"]["WorkspaceRole"];
                    };
                };
            };
            responses: {
                /** @description Role mis a jour */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceMemberDto"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Refuse un workspace sans Admin restant */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les projets d'un workspace */
        get: {
            parameters: {
                query?: {
                    includeArchived?: boolean;
                };
                header?: never;
                path: {
                    workspaceId: components["parameters"]["WorkspaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des projets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDto"][];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Creer un projet */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["WorkspaceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        description?: string | null;
                    };
                };
            };
            responses: {
                /** @description Projet cree */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDto"];
                    };
                };
                400: components["responses"]["ValidationError"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recuperer un projet */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Le projet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDto"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifier un projet */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        description?: string | null;
                    };
                };
            };
            responses: {
                /** @description Projet modifie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDto"];
                    };
                };
                400: components["responses"]["ValidationError"];
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/api/projects/{projectId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archiver un projet */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Projet archive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDto"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister/filtrer/rechercher les taches d'un projet */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["TaskItemStatus"];
                    assignedUserId?: string;
                    priority?: components["schemas"]["TaskPriority"];
                    search?: string;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page de taches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskItemPage"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Creer une tache */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        description?: string | null;
                        priority: components["schemas"]["TaskPriority"];
                        /** Format: date */
                        dueDate?: string | null;
                    };
                };
            };
            responses: {
                /** @description Tache creee */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskItemDto"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Projet archive, creation refusee */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recuperer le detail d'une tache */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detail de la tache */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskItemDetailDto"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifier titre, description, priorite ou echeance */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        description?: string | null;
                        priority?: components["schemas"]["TaskPriority"];
                        /** Format: date */
                        dueDate?: string | null;
                    };
                };
            };
            responses: {
                /** @description Tache modifiee */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskItemDto"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/tasks/{taskId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Deplacer la tache vers un nouveau statut (drag and drop) */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Jeton de concurrence (version de la tache), pour detecter un conflit */
                    "If-Match"?: string;
                };
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["TaskItemStatus"];
                    };
                };
            };
            responses: {
                /** @description Statut mis a jour */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskItemDto"];
                    };
                };
                /** @description Transition invalide OU conflit de concurrence */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Transition refusee par une regle metier (ex. Done sans assigne) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/assignee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assigner la tache a un utilisateur (remplace l'assignation existante) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        userId: string;
                    };
                };
            };
            responses: {
                /** @description Tache assignee */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskItemDto"];
                    };
                };
                /** @description Utilisateur non membre du workspace du projet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        /** Retirer l'assignation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tache desassignee */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskItemDto"];
                    };
                };
                /** @description Refuse si la tache est Done (regle metier) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les commentaires d'une tache (paginee) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page de commentaires */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentDto"][];
                    };
                };
            };
        };
        put?: never;
        /** Ajouter un commentaire */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                    };
                };
            };
            responses: {
                /** @description Commentaire cree */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Supprimer un commentaire (auteur ou Admin uniquement) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supprime */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister mes notifications (paginee) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page de notifications */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marquer une notification comme lue */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notificationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification mise a jour */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marquer toutes les notifications comme lues */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fait */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetails: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            traceId?: string;
        };
        ValidationProblemDetails: components["schemas"]["ProblemDetails"] & {
            errors?: {
                [key: string]: string[];
            };
        };
        /** @enum {string} */
        TaskItemStatus: "ToDo" | "InProgress" | "InReview" | "Done";
        /** @enum {string} */
        TaskPriority: "Low" | "Medium" | "High" | "Urgent";
        /** @enum {string} */
        WorkspaceRole: "Member" | "Admin";
        /** @enum {string} */
        ProjectStatus: "Active" | "Archived";
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAtUtc?: string;
            user?: components["schemas"]["UserDto"];
        };
        UserDto: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            fullName?: string;
        };
        WorkspaceDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: date-time */
            createdAt?: string;
            myRole?: components["schemas"]["WorkspaceRole"];
        };
        WorkspaceMemberDto: {
            /** Format: uuid */
            userId?: string;
            /** Format: email */
            email?: string;
            fullName?: string;
            role?: components["schemas"]["WorkspaceRole"];
        };
        ProjectDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            workspaceId?: string;
            name?: string;
            description?: string | null;
            status?: components["schemas"]["ProjectStatus"];
            /** Format: date-time */
            createdAt?: string;
            taskCount?: number;
        };
        TaskItemDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            projectId?: string;
            title?: string;
            description?: string | null;
            status?: components["schemas"]["TaskItemStatus"];
            priority?: components["schemas"]["TaskPriority"];
            /** Format: date */
            dueDate?: string | null;
            /** Format: uuid */
            assignedUserId?: string | null;
            assignedUserName?: string | null;
            commentCount?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        TaskItemDetailDto: components["schemas"]["TaskItemDto"] & {
            comments?: components["schemas"]["CommentDto"][];
        };
        TaskItemPage: {
            items?: components["schemas"]["TaskItemDto"][];
            page?: number;
            pageSize?: number;
            totalCount?: number;
        };
        CommentDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            taskId?: string;
            content?: string;
            /** Format: uuid */
            authorId?: string;
            authorName?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        NotificationDto: {
            /** Format: uuid */
            id?: string;
            message?: string;
            isRead?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            relatedTaskId?: string | null;
        };
    };
    responses: {
        /** @description Token absent ou invalide */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authentifie mais non autorise sur cette ressource */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Ressource introuvable */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Erreur de validation des champs envoyes */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
    };
    parameters: {
        WorkspaceId: string;
        ProjectId: string;
        TaskId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
